[package]
name = "using_generic_imple_multiple_same_trait_for_one_generic_struct_with_different_type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
